---
- name: Install required packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - apt-transport-https
    install_recommends: yes
    update_cache: yes
    state: present

- name: Remove old conflicting versions
  apt:
    pkg:
     - docker.io
     - docker-compose
     - docker-doc
     - podman-docker
    state: absent

- name: Create /etc/apt/keyrings directory with correct permissions
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Docker | Pridat docker repozitar
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Docker | Instalace
  apt:
    pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    install_recommends: yes
    update_cache: yes
    state: present
...
